/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-11-07 at 22:41:18 UTC 
 * Modify at your own risk.
 */

package com.appspot.qikexpress.groceryitemsoperations.model;

/**
 * Model definition for GroceryItem.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the groceryitemsoperations. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GroceryItem extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catLev1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catLev2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catLev3;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String catLev4;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groceryId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer groceryItemId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groceryItemImage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String groceryItemName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float groceryItemPriceValue;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCatLev1() {
    return catLev1;
  }

  /**
   * @param catLev1 catLev1 or {@code null} for none
   */
  public GroceryItem setCatLev1(java.lang.String catLev1) {
    this.catLev1 = catLev1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCatLev2() {
    return catLev2;
  }

  /**
   * @param catLev2 catLev2 or {@code null} for none
   */
  public GroceryItem setCatLev2(java.lang.String catLev2) {
    this.catLev2 = catLev2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCatLev3() {
    return catLev3;
  }

  /**
   * @param catLev3 catLev3 or {@code null} for none
   */
  public GroceryItem setCatLev3(java.lang.String catLev3) {
    this.catLev3 = catLev3;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCatLev4() {
    return catLev4;
  }

  /**
   * @param catLev4 catLev4 or {@code null} for none
   */
  public GroceryItem setCatLev4(java.lang.String catLev4) {
    this.catLev4 = catLev4;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroceryId() {
    return groceryId;
  }

  /**
   * @param groceryId groceryId or {@code null} for none
   */
  public GroceryItem setGroceryId(java.lang.String groceryId) {
    this.groceryId = groceryId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getGroceryItemId() {
    return groceryItemId;
  }

  /**
   * @param groceryItemId groceryItemId or {@code null} for none
   */
  public GroceryItem setGroceryItemId(java.lang.Integer groceryItemId) {
    this.groceryItemId = groceryItemId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroceryItemImage() {
    return groceryItemImage;
  }

  /**
   * @param groceryItemImage groceryItemImage or {@code null} for none
   */
  public GroceryItem setGroceryItemImage(java.lang.String groceryItemImage) {
    this.groceryItemImage = groceryItemImage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGroceryItemName() {
    return groceryItemName;
  }

  /**
   * @param groceryItemName groceryItemName or {@code null} for none
   */
  public GroceryItem setGroceryItemName(java.lang.String groceryItemName) {
    this.groceryItemName = groceryItemName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getGroceryItemPriceValue() {
    return groceryItemPriceValue;
  }

  /**
   * @param groceryItemPriceValue groceryItemPriceValue or {@code null} for none
   */
  public GroceryItem setGroceryItemPriceValue(java.lang.Float groceryItemPriceValue) {
    this.groceryItemPriceValue = groceryItemPriceValue;
    return this;
  }

  @Override
  public GroceryItem set(String fieldName, Object value) {
    return (GroceryItem) super.set(fieldName, value);
  }

  @Override
  public GroceryItem clone() {
    return (GroceryItem) super.clone();
  }

}
